### ISSUE TITLE
Ionic + Capacitor = Incompatible? (First Party Consent)

### ISSUE THREAD

**Issue by ntziolis** [auth0-samples/auth0-ionic4-samples#10]
@davidpatrick Addressing this to you since you have committed the ionic 4 docs. 

When using capacitor the urls on the device are:
- capacitor://localhost (ios)
- http://localhost (android)

This leads to forced first party consent from auth0 due the auth callback is to localhost.
- Is there any way to prevent forced first party consent on localhost even if we have to disable it globally for the entire tenant?
- Or is auth0 at this point simply not compatible with capacitor if you want to prevent first party consent?

Note:
Changing from localhost to a custom host name is theoretically possible but practically not as localhost is considered a secure context to call web apis on the device. If one would change the hostname the user would see multiple approval requests for e.g camera access (one OS one webview). So this really isn't an option.

I have outlined the situation in more detail on the community forum as well:
https://community.auth0.com/t/how-to-prevent-first-party-app-consent-when-using-auth0-ionic-capacitor/54007

**Comment by frederikprijck** [comment]
I don't think there is much we can do about this from the SDK side of things, as Auth0 never considers localhost being a verifiable first-party application (because any malicious application may run on `localhost` for a user): https://auth0.com/docs/authorization/user-consent-and-third-party-applications#skip-consent-for-first-party-applications.

As I think this is outside of the reach of the SDK or sample application, I think the community post is a better place, or reaching out to our support team.

Closing this here, but feel free to continue the conversation.

**Comment by ntziolis** [comment]
>We are compatible, but we do not consider localhost being a first party application.

It might generally work. But for the purposes of building apps with capacitor this means you are not fully compatible if I cannot prevent users to see a consent page for first party apps.

We understand localhost is generally considered unsafe, but we would ask to have an option to disable this requirement (other auth providers allow todo this as well). Totally fine if it comes with a gigantic warning and a liability waver. But not having the option blocks usage from capacitor if forced consent is a showstopper for your devs. Unless you know of a workaround that we are unfamiliar with. In which case we would kindly ask to share here or in the community post.

For others that are looking for capacitor + auth0:
- Yes its possible to integrate auth0 + capacitor (via ionic-appauth npm package which uses appauth-js)
- But your users will be presented with a consent page on first login + every time you change the requested scopes

What does that mean:
- If you are like us using a third party provider for logins (like google, facebook apple etc) on first login (and all scope changes)
 - your users will be presented with the consent screen from the third party provider 
  - AND afterwards users will be presented with a consent screen for your own app

We have measured this and saw a 30% drop on the second consent screen. This is enough of a concern for us to move away from auth0. We really want to avoid this since we much prefer it to other auth providers.

**Comment by ntziolis** [comment]
@frederikprijck I wanted to let you and others that fid this thread know that we found a solution.

It does requires setting:
- setting deeplinks for the app ([see here how to set up deeplinks in in capacitor](https://capacitorjs.com/docs/guides/deep-links))
- making the callback page reachable via deeplink
- and then provide the deeplink based callback as redirect url during authorization

@frederikprijck I'd be happy to share our end-to end solution using ionic-appauth (free npm package), for you to crate an ionic capacitor + auth0 guide if you are interested.

**Comment by frederikprijck** [comment]
@ntziolis If you are willing to share your end to end solution that would be great, we are definitely interested in that. Thanks!
