### ISSUE TITLE
Err_Name_Not_Resolved

### ISSUE THREAD

**Issue by Sprinton** [auth0-samples/auth0-ionic4-samples#9]
Hello,
By Downloading the Ionic4 Sample App from here https://auth0.com/docs/quickstart/native/ionic4#install-the-dependencies
and running it, i get the error in the attached image.

![image](https://user-images.githubusercontent.com/58607711/80010287-818d4200-84ca-11ea-8eb1-5b6f5dca2353.png)

**Comment by Widcket** [comment]
Hi @Sprinton, that looks like a connectivity issue on your end.
